### ISSUE TITLE
Tasks2019

### ISSUE THREAD

**Issue by andyceo** [ergoplatform/ansible#2]
## Actual Devops Tasks

- [x] Write crontab daemon in Docker Swarm (nginx must periodically reload nginx configuration and report status about into monitoring). see #6 
- [ ] Rewrite Faucet (see https://github.com/ergoplatform/faucet/issues/1, https://github.com/ergoplatform/faucet/issues/2)
- [ ] Update openapi-checker to recent version: https://github.com/ergoplatform/ergo/issues/922
- [ ] Autodeploy for ergoplatform.org website
- [ ] ergoplatform sites monitoring (http response 200 OK)
- [ ] ergoplatform sites SSL monitoring (see https://www.influxdata.com/blog/monitoring-tls-certificates-with-telegraf/)
- [ ] explorers height monitoring
- [ ] Alerts for explorers heights not growing into slack
- [ ] Alerts for sites crashes into slack
- [ ] Alerts for SSL certificates into slack
- [ ] Remove nginx params for mainnet launch
- [ ] Alert for 'Docker Hub build done'  for ergoplatform projects into slack
- [x] Docpage for explorer team in Ansible repo (see https://github.com/ergoplatform/ansible/pull/9)
- [ ] PostgreSQL monitoring in Grafana
- [ ] PostgreSQL slow queries log
- [ ] Add Python library for secrets and signing txs into ergo-libs
- [ ] Compile https://github.com/ScorexFoundation/ScorexTutorial and put to https://docs.ergoplatform.com/ 
- [ ] add delay to dockerhub-webhook to make sure new image ready to download
- [x] Initial commits for ergo-libs repository
- [x] Infrastructure description into Ansible repo

### Backlog (ideas)

- [ ] it tests parallel execution
- [ ] benchmarks
- [ ] Choose solution for logs, between Loki and ELK
- [ ] Ergo libs for PHP
- [ ] ergo-node-monitoring multi-threading rewrite
- [ ] Create 'awsome' repo - curated list of libs, projects and services, related to Ergo
- [ ] Ubuntu 18.04 upgrade
- [ ] OpenLDAP for Ergo
- [ ] OpenVPN
- [ ] Network protocol documentation
- [ ] Prettify and customize Grafana dashboards
- [ ] Android lite node native implementation (NiPoPow) (!)
- [ ] Alerts for Let's Encrypt certificates (notify if going to expire)
- [ ] Testnet-1 tests in different java
- [ ] Testnet-1 test docker

## Done

- testnet 1.9 (deploy + monitoring)
- LaTeX
- добавить kill -9 в задачу ergo-deploy-to-testnet
- alerting (kapacitor)
    - какая-то нода не даёт данные более 2 минут, уведомление
    - высота не растет у какой-то ноды более 10 минут, уведомление
